export POSTGRES_USER=<DB_USER>
export POSTGRES_PWD=<DB_PASSWD>
export POSTGRES_DB=<DATABASE_NAME>
export POSTGRES_MAX_OPEN_CONNS=25
export POSTGRES_MAX_IDLE_CONNS=25
export POSTGRES_MAX_IDLE_TIME=15m
export MOVIES_API_LOG_LEVEL=1 #0=Debug/1=INFO/2=ERROR/3=FATAL/4=OFF